### PR TITLE
add ReproTea x repliCATS event

### PR DESCRIPTION
**Pull request by eirini-zormpa**
when reviewing the pull request, could you also check the registration form? Thanks :)

### CODE REVIEW

**Comment by eirini-zormpa** [comment]
amazing, thank you 😊  do you think you could tweet from the oscn account about it at some point today?

**Comment by KristijanArmeni** [comment]
Yes, sure! I will be out of office until 16ish today, so can do tweet about Replicats later in the afternoon.

If anyone else (@jeanette-mostert or @johalgermissen) wants to tweet about it earlier in the day, feel free to go ahead.

**Comment by johalgermissen** [comment]
Yeah 😸 I'll tweat it right now

**Comment by johalgermissen** [comment]
öhm @KristijanArmeni The webpage is .../reprocats but the event is called replicats... by intention or not? 😂 Also not sure whether we should change it because now it's tweated... anyway

**Comment by eirini-zormpa** [comment]
I called reprocats because it's a collaboration between reproducibilitea and replicats 🤷‍♀

**Pull request merged**
